### ISSUE TITLE
Can't Hide on Gridless Maps

### ISSUE THREAD

**Issue by kurisu-n** [CarlosFdez/world-explorer#19]
The module seems to reveal a gridless map in “square brush” way, with the square's top left corner located on the cursor. The main issue is that hiding the map again doesn't seem to be working at all. Additionally, it would be great if there were more options for this, like a circular brush or a way to adjust the size.

**Comment by CarlosFdez** [comment]
I have no idea why I didn't get a notification. So sorry for the late reply.

The module is not designed for a gridless map. It even working at all is a bit weird, but its designed around grid revealing, not map revealing. For something more free form, I think you want simple fog, which works via drawing into fog of war rather than maintaining a list of revealed tiles.
