### ISSUE TITLE
v10 version seems to only obscure the background image, not additional tiles

### ISSUE THREAD

**Issue by Arkensald** [CarlosFdez/world-explorer#27]
This used to be a feature in v9, so I'm not sure what happened. I even went through and made a brand new world with only world explorer installed, and the issue can be seen on the default intro page.
![Capture](https://user-images.githubusercontent.com/91648271/204940038-21fb2566-7085-4d8c-90bf-2bc8e56478cf.PNG)
Here we see that the background image is obscured (I even made a few squares visible just to demonstrate), however the logo in the middle (which is not a foreground image, by the way) is not obscured at all.

I'm using the most recent version of v10 and the Pathfinder 2e system, if that helps.

I hope there's a solution! This is one of the last modules I'm holding out on before fully upgrading to v10 for my main campaign.

**Comment by CarlosFdez** [comment]
I posted in the reddit, and this is a long time reply, but this is intentional. Tiles can be used to show resources and such, and the world explorer's purpose is to hide the map.

That said, perhaps there's merit in treating overhead tiles separately from non-overhead tiles. It will be tricky but I'll need to look into it. Unfortunately PF2e development is a lot of work. I'd accept a PR if someone wants to dig into it (so long as they do it well).

**Comment by CarlosFdez** [comment]
Actually no that won't work. The only way to really handle this I guess, if its possible in v10 to obscure tiles while still showing the grid layer, is to set it as an option at the scene level. I don't think there's any way to consolidate the "tiles as part of the map" and "tiles to denote resources and such" crowds.

**Comment by CarlosFdez** [comment]
This should now be resolved. I managed to find a way to get it to work that should solve all use cases.
