### ISSUE TITLE
Scene Switch Loading Error

### ISSUE THREAD

**Issue by Vildara42** [CarlosFdez/world-explorer#37]
When I have the module loaded, it will throw up an error when I switch scenes. The scene never switches and I have to close out of Foundry to resolve it. 
![image](https://github.com/CarlosFdez/world-explorer/assets/64794585/77279db9-033c-40b9-bca7-63971a2e497d)

**Comment by sneat** [comment]
FYI @Vildara42 this issue happens if you switch to a scene that does _not_ have World Explorer enabled on it, and then switch to one that does while still having the World Explorer tool/control selected.

When you move to the scene that doesn't have it enabled on the scene, it tries to select the tool/control that doesn't exist on the canvas (the tool doesn't show on a scene that doesn't have World Explorer enabled).

The workaround is to change to one of the other controls (e.g. Actor) before switching scenes.

**Comment by CarlosFdez** [comment]
Thanks for the bug report. That's definitely an odd bug.

**Comment by CarlosFdez** [comment]
Seems to be a core issue. I reported it, but I"ll have to find a way to work around it. One thought I had was to put the world explorer stuff in token controls for map reveal stuff, and in lighting controls for the reset.

**Comment by CarlosFdez** [comment]
Worked around in World Explorer version 0.9.0.
