### ISSUE TITLE
Save explored area when token moves

### ISSUE THREAD

**Issue by St1ck2k** [CarlosFdez/world-explorer#6]
This module is awesome for my campaing (and in general), yet manual area reveal is a small drawback for me to use it at it's fullest.

I really hope I'm not saying something stupid and ignorant, but you already can **permanently** reveal area on mouse click, why can't you do the same when token moves?

**Comment by CarlosFdez** [comment]
The reason its like that is because it was designed for Pathfinder 2e where reconnoitering is a special action. An area is not properly revealed until its actually investigated.

That said it would be worth having as a feature. Next thing I might do once I find time is brush reveal, but if someone wants to expedite adding in token fog reveal (would it be a scene setting? Actual setting?) in a pull request I can get it in earlier.

**Comment by St1ck2k** [comment]
Understood! Thanks for the answer

**Comment by CarlosFdez** [comment]
Implemented thanks to @IrmatDen and available in version 0.3.
